name: Help downloading / installing hosted files
description: I tried to download / install a hosted file and it didn't work as expected. Tell us what using this form!
title: "[Help]: filename / resource here (replace by the file you are trying to get help with)"
assignees:
  - vonschappler
labels:
  - help section
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Please describe which improvements can be done into the **Help** section of the application.
  
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: "I need help with:"
      description: Select the option that fits the type of suggestion.
      options:
        - Downloading a provided resource
        - Installing a provided resource
        - A required dependency is missing in the resources provided
        - Other (specify in the description with a detailed explanation)
  
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Provide a detailed description of what you need help with:"
      description: "A detailed description of what you need help with is important so can work on it."
      placeholder: |
        Please add as much details as possible from what you need help with. Screenshots can be added here (and   preferred to speed up the evaluation of the case)
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Contact information:
  
  - type: dropdown
    id: contact
    attributes:
      description: Let us know if you want to be contacted directly about the progress of work into this.
      label: "Do you want to be contacted about this issue?"
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  
  - type: input
    id: email
    attributes:
      label: "Email:"
      description: If you select "Yes" above, please provide your email address so that we can contact you about this feature request.
      placeholder: myemail@example.com
  
  - type: checkboxes
    id: consent
    attributes:
      label: 'Consentient:' 
      options:
        - label: By selecting "Yes" and providing my e-mail, I understand that the developer won't be using it for any other purposes than contacting me about this issue.
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Terms:

  - type: checkboxes
    id: terms
    attributes:
      label: 'Agreement:' 
      options:
        - label: I understand that by submitting this, nothing will be answered or resolved immediately.
          required: true
        - label: By submitting this request for help, I understand that the developer will use the information provided here to help me with my request.
          required: true
        - label: I certify that I had tested all possibilities and suggestions provided by the developer before submitting this request for help.
          required: true
        - label: I am **AWARE** about everything mentioned in the[**License**](./blob/main/License.md) file for this project.
          required: true
