name: Help downloading / installing hosted files
description: I tried to download / install a hosted file and it didn't work as expected. Tell us what using this form!
title: "[Help]: filename / resource here (replace by the file you are trying to get help with)"
assignees:
  - vonschappler
labels:
  - help section
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Please describe which improvements can be done into the **Help** section of the application.
  
  - type: dropdown
    id: type
    validations:
      required: true
    attributes:
      label: "I need help with:"
      description: Select the option that fits the type of suggestion.
      options:
        - Downloading a provided resource
        - Installing a provided resource
  
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Please provide a detailed description of what you need help with:"
      description: "A detailed description of what you need help with is important so can work on it."
      placeholder: |
        Please add as much details as possible from what you need help with. Screenshots can be added here, if you judge necessary.
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Contact information:
  
  - type: dropdown
    id: contact
    attributes:
      description: Let us know if you want to be contacted directly about the progress of work into this.
      label: "Do you want to be contacted about this issue?"
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  
  - type: input
    id: email
    attributes:
      label: "Email:"
      description: If you select "Yes" above, please provide your email address so that we can contact you about this feature request.
      placeholder: myemail@example.com
  
  - type: checkboxes
    id: consent
    attributes:
      label: 'Consentient:' 
      options:
        - label: By selecting "Yes" and providing my e-mail, I understand that the developer won't be using it for any other purposes than contacting me about this issue.
  
  - type: markdown
    attributes:
      value: |
        ---
        ## Terms:

  - type: checkboxes
    id: terms
    attributes:
      label: 'Agreement:' 
      options:
        - label: I agree that by submitting this report the information listed here are suggestions that aim to improve the application.
          required: true
        - label: I understand that my request may take some time to be attended, and the proposal for improvements I suggested may not be accepted, hence not applied to the application.
          required: true
